/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./../components/ai-assistant/index.vue')['default']
    AutoForm: typeof import('./../components/common/auto-form/index.vue')['default']
    ButtonGroup: typeof import('./../components/common/button-group/index.vue')['default']
    CaptureSnapshot: typeof import('./../components/service-management/components/capture-snapshot.vue')['default']
    ChatHistory: typeof import('./../components/ai-assistant/chat-history.vue')['default']
    ChatInput: typeof import('./../components/ai-assistant/chat-input.vue')['default']
    ChatMessage: typeof import('./../components/ai-assistant/chat-message.vue')['default']
    ComponentAssigner: typeof import('./../components/create-service/components/component-assigner.vue')['default']
    ComponentInstaller: typeof import('./../components/create-service/components/component-installer.vue')['default']
    Components: typeof import('./../components/service-management/components.vue')['default']
    Configs: typeof import('./../components/service-management/configs.vue')['default']
    Create: typeof import('./../components/create-service/create.vue')['default']
    CustomProgress: typeof import('./../components/job/custom-progress.vue')['default']
    Empty: typeof import('./../components/common/empty/index.vue')['default']
    EmptyContent: typeof import('./../components/ai-assistant/empty-content.vue')['default']
    FilterForm: typeof import('./../components/common/filter-form/index.vue')['default']
    HeaderCard: typeof import('./../components/common/header-card/index.vue')['default']
    Job: typeof import('./../components/job/index.vue')['default']
    JobModal: typeof import('./../components/job-modal/index.vue')['default']
    LogView: typeof import('./../components/log-view/index.vue')['default']
    MainCard: typeof import('./../components/common/main-card/index.vue')['default']
    MarkdownView: typeof import('./../components/common/markdown-view/index.vue')['default']
    Overview: typeof import('./../components/service-management/overview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLang: typeof import('./../components/select-lang/index.vue')['default']
    ServiceConfigurator: typeof import('./../components/create-service/components/service-configurator.vue')['default']
    ServiceManagement: typeof import('./../components/service-management/index.vue')['default']
    ServiceSelector: typeof import('./../components/create-service/components/service-selector.vue')['default']
    SnapshotManagement: typeof import('./../components/service-management/components/snapshot-management.vue')['default']
    StatusDot: typeof import('./../components/common/status-dot/index.vue')['default']
    SvgIcon: typeof import('./../components/common/svg-icon/index.vue')['default']
    Template: typeof import('./../components/common/auto-form/template.vue')['default']
    ThemeSwitch: typeof import('./../components/theme-switch/index.vue')['default']
    TreeSelector: typeof import('./../components/create-service/components/tree-selector.vue')['default']
    UserAvatar: typeof import('./../components/user-avatar/index.vue')['default']
  }
}
